import { createRoot } from "react-dom/client";
import "../src/poppy/poppy-ui.css";
import "../src/styles.css";
import "../src/brand-overrides.css";
import "../src/login.css";
import "../src/budget-operations.css";
import "../src/finance-enhancements.css";
import "../src/budget-live.css";
import "../src/operations-live.css";
import "../src/home-live.css";
import "../src/auth-overrides.css";
import "../src/kokode-reporting.css";
import "../src/kokode-reporting-status.css";
import "../src/poppy-service-bar.css";
import "../src/poppy/poppy-shell.css";
import { BrowserRouter } from "react-router";
import App from "../src/App";
import FinanceEnhancements from "../src/FinanceEnhancements";
createRoot(document.getElementById("root")!).render(<BrowserRouter basename="/finance"><App/><FinanceEnhancements/></BrowserRouter>);
